name: CD
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'

env:
  gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
  region: ${{ secrets.GCP_REGION }}
  artifact_registry_url: ${{ secrets.GCP_REGION }}-docker.pkg.dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setting up GCloud & Docker
      - name: Google Cloud Authentification
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Authorize Docker push
        run: gcloud auth configure-docker $artifact_registry_url
      # Fetching node modules from cache or installing them
      - name: Get node_modules from cache or install
        id: node-modules
        uses: actions/cache@v3
        env:
          cache-name: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-cache-${{ env.cache-name }}-
      - name: Install Dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: npm ci
      # NX monorepo setup, testing building and deploying
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
      - run: npx nx build admin-ui
      - name: Build and Push Image
        run: |-
          docker build -f apps/admin-ui/Dockerfile -t $artifact_registry_url/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/admin-ui .
          docker push $artifact_registry_url/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/admin-ui
      - run: npx nx deploy admin-ui
